//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class Anime
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Anime()
        {
            this.AnimeCollection = new HashSet<AnimeCollection>();
            this.AnimeGenre = new HashSet<AnimeGenre>();
        }
    
        public int animeId { get; set; }
        public Nullable<int> studioId { get; set; }
        public string name { get; set; }
        public int episodes { get; set; }
        public System.DateTime aired { get; set; }
        public string status { get; set; }
        public int duration { get; set; }
        public Nullable<int> rating { get; set; }
        public string type { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimeCollection> AnimeCollection { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<AnimeGenre> AnimeGenre { get; set; }
        public virtual Studio Studios { get; set; }
    }
}
