//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_DAL
{
    using System;
    using System.Collections.Generic;
    
    public partial class AnimeGenre
    {
        public int animeGenreId { get; set; }
        public int animeId { get; set; }
        public Nullable<int> genreId { get; set; }
    
        public virtual Anime Animes { get; set; }
        public virtual Genre Genres { get; set; }
    }
}
