//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MAL_DAL
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class Project_MALEntities : DbContext
    {
        public Project_MALEntities()
            : base("name=Project_MALEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Anime> Anime { get; set; }
        public virtual DbSet<AnimeCollection> AnimeCollection { get; set; }
        public virtual DbSet<AnimeGenre> AnimeGenre { get; set; }
        public virtual DbSet<Collection> Collection { get; set; }
        public virtual DbSet<Genre> Genre { get; set; }
        public virtual DbSet<Studio> Studio { get; set; }
        public virtual DbSet<User> User { get; set; }
    }
}
